{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ce15c5d4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import joblib\n",
    "\n",
    "# 모델 불러오기\n",
    "@st.cache_resource\n",
    "def load_model():\n",
    "    return joblib.load('best_model.pkl')\n",
    "\n",
    "model = load_model()\n",
    "\n",
    "# 데이터 불러오기\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    return pd.read_csv('DS_Customer_data_modified2.csv')\n",
    "\n",
    "df = load_data()\n",
    "\n",
    "st.title('고객 이탈 예측 대시보드')\n",
    "\n",
    "# 1. 신규 고객 데이터 입력\n",
    "st.header('1. 신규 고객 데이터 입력')\n",
    "columns = df.columns.tolist()\n",
    "columns = [col for col in columns if col not in ['고객이탈여부', '고객ID']]  # 예측에 사용하지 않을 열 제외\n",
    "\n",
    "new_customer = {}\n",
    "for col in columns:\n",
    "    if df[col].dtype == 'object':\n",
    "        options = df[col].unique().tolist()\n",
    "        new_customer[col] = st.selectbox(f'{col} 선택', options)\n",
    "    else:\n",
    "        new_customer[col] = st.number_input(f'{col} 입력', value=float(df[col].mean()))\n",
    "\n",
    "# 2. 이탈 확률 예측\n",
    "if st.button('이탈 확률 예측'):\n",
    "    input_data = pd.DataFrame([new_customer])\n",
    "    \n",
    "    # 범주형 변수 인코딩 (필요 시)\n",
    "    for col in input_data.select_dtypes(include=['object']):\n",
    "        input_data[col] = input_data[col].astype('category').cat.codes\n",
    "    \n",
    "    churn_prob = model.predict_proba(input_data)[0][1]\n",
    "    st.write(f'이 고객의 이탈 확률은 {churn_prob:.2%}입니다.')\n",
    "\n",
    "    # 3. 분포 시각화 (신규 고객과 기존 데이터 비교)\n",
    "    st.header('3. 고객 데이터 분포 비교')\n",
    "    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()\n",
    "    selected_col = st.selectbox('비교할 특성 선택', numeric_cols)\n",
    "    \n",
    "    fig, ax = plt.subplots()\n",
    "    sns.histplot(data=df, x=selected_col, kde=True, ax=ax)\n",
    "    ax.axvline(new_customer[selected_col], color='r', linestyle='--')\n",
    "    ax.set_title(f'{selected_col} 분포')\n",
    "    st.pyplot(fig)\n",
    "\n",
    "    percentile = sum(df[selected_col] < new_customer[selected_col]) / len(df) * 100\n",
    "    st.write(f'이 고객의 {selected_col}는 상위 {100-percentile:.2f}%에 해당합니다.')\n",
    "\n",
    "    # 4. 기존 고객 평균과 비교\n",
    "    st.header('4. 기존 고객 평균과 비교')\n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "    x = np.arange(len(numeric_cols))\n",
    "    width = 0.35\n",
    "\n",
    "    avg_values = df[numeric_cols].mean()\n",
    "    new_values = [new_customer[col] for col in numeric_cols]\n",
    "\n",
    "    ax.bar(x - width/2, avg_values, width, label='기존 고객 평균')\n",
    "    ax.bar(x + width/2, new_values, width, label='신규 고객')\n",
    "\n",
    "    ax.set_xticks(x)\n",
    "    ax.set_xticklabels(numeric_cols, rotation=45, ha='right')\n",
    "    ax.legend()\n",
    "    ax.set_title('신규 고객과 기존 고객 평균 비교')\n",
    "\n",
    "    st.pyplot(fig)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
